version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: product-service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: product_db
      MYSQL_USER: product_user
      MYSQL_PASSWORD: product_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - product-network

  product-service:
    build:
      context: ./core-services/product-service
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/product_db
      SPRING_DATASOURCE_USERNAME: product_user
      SPRING_DATASOURCE_PASSWORD: product_password
    depends_on:
      - mysql
    networks:
      - product-network

volumes:
  mysql-data:

networks:
  product-network:
    driver: bridge